name: FL provision resources

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource group name'
        required: true
        default: 'fedlearn' 
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: '{"clientId":"3df1cb10-d191-443e-a16c-2a4a0a3be2f5","clientSecret":"1Th8Q~NBef_6WRaPgYhyQELwpbtigTHRqjMIxbsC","subscriptionId":"d8a028c8-5d18-4673-8524-e68732c4a04a","tenantId":"d48f2fdb-cd54-4bef-917f-600541d87d4f"}'
    - name: Provision resources
      run: |
        az configure --defaults group="${{ github.event.inputs.resource_group }}"
        RANDOMQUALIFIER="$RANDOM"

        az vm create -n fedserver --image microsoft-dsvm:ubuntu-1804:1804-gen2:latest --authentication-type password --public-ip-address-dns-name ${{ github.event.inputs.resource_group }} \
        --admin-password ${{ secrets.VM_PASSWORD }}

        az vm open-port -n fedserver --port 8002-8003 --priority 100

        az ml workspace create -n Asia-Hospital --location eastasia
        az ml compute create --type ComputeInstance --name FedClientAsia$RANDOMQUALIFIER --workspace-name Asia-Hospital

        az ml workspace create -n Europe-Hospital --location westeurope
        az ml compute create --type ComputeInstance --name FedClientEurope$RANDOMQUALIFIER --workspace-name Europe-Hospital

        az ml workspace create -n US-Hospital --location eastus
        az ml compute create --type ComputeInstance --name FedClientUS$RANDOMQUALIFIER --workspace-name US-Hospital
